blog/config/routes.rb
Rails.application.routes.draw do
  
  

  
  resources :categories

  resources :articles do
    resources :comments, only: [:create, :destroy, :update, :show]
  end

  devise_for :users

  root 'welcome#index'

  get "/dashboard", to:'welcome#dashboard' 

  put "/articles/:id/publish", to:'articles#publish'

end

blog/app/models/article.rb
class Article < ActiveRecord::Base
	include AASM

	belongs_to :user
	has_many :comments
	has_many :has_categories
	has_many :categories, through: :has_categories

	validates :title, {presence:true, uniqueness: true}
	validates :body, {presence:true, length: {minimum:20}}

	before_save :set_visit_counts
	after_create :save_categories
	after_create :send_email

	has_attached_file :cover, style: { medium: "1200x700", thumb: "800x600" }
	#Validación de seguridad
	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/

	scope :publicados, ->{ where(state: "published") }

	scope :ultimos, ->{ order("created_at DESC") }


	aasm column: 'state' do
		state :in_draft, initial:true
		state :published

		event :publish do
			transitions from: :in_draft, to: :published
		end

		event :unpublish do
			transitions from: :published, to: :in_draft
		end
	end

	#Custom Setter
	def categories=(value)
		@categories = value
	end

	def update_visit_counts
		self.save if self.visit_counts.nil?
		self.update(visit_counts: self.visit_counts+1)
	end

	private 
	def send_email
		ArticleMailer.new_article(self)
	end

	def save_categories
		unless @categories.nil?
			@categories.each do |category_id|
				HasCategory.create category_id: category_id, article_id: self.id
			end
		end
	end
	def set_visit_counts
		#Asigna cero solo si es nil visit_counts
		self.visit_counts ||= 0
	end
end

blog/app/models/category.rb
class Category < ActiveRecord::Base
	validate  :name, presence: true;
	has_many :has_categories
	has_many :articles, through: :has_categories
end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

blog/app/models/concerns/permissions_concern.rb
module PermissionsConcern extend ActiveSupport::Concern
	def is_normal_user?
		self.permission_level >= 1
	end

	def is_editor?
		self.permission_level >= 2
	end

	def is_admin?
		self.permission_level >= 3
	end
end

blog/app/models/has_category.rb
class HasCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

blog/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
  has_many :comments

  include PermissionsConcern

  def avatar
  	email_address = self.email.downcase
 
	# create the md5 hash
	hash = Digest::MD5.hexdigest(email_address)
	 
	# compile URL which can be used in <img src="RIGHT_HERE"...
	image_src = "https://www.gravatar.com/avatar/#{hash}"
  end
  
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_catg


  protected

  def authenticate_editor!
  	redirect_to root_path unless user_signed_in? && current_user.is_editor?
  end

  def authenticate_admin!
  	redirect_to root_path unless user_signed_in? && current_user.is_admin?
  end

  private
  
  def set_catg
  	@catgs = Category.all
  end


end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, except: [:show, :index]

	before_action :authenticate_editor!, only: [:new, :create, :update]

	before_action :authenticate_admin!, only: [:destroy]

	#GET articles
	def index
		#Active record :)
		@articles = Article.paginate(page: params[:page], per_page:9).publicados.ultimos
	end

	#GET articles/:id
	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
		@article.update_visit_counts
	end

	#GET articles/new
	def new
		#Hasta ahi no existe en BD
		@article= Article.new
	end

	#POST /articles
	def create
		#@article = Article.new(title: params[:article][:title],body: params[:article][:body])
		@article = current_user.articles.new(article_params)
		@article.categories = params[:categories]
		if @article.valid?
			@article.save
			redirect_to @article
		else
			#Le decimos que renderice la vista new.
			render :new
		end
	end

	#DELETE /article
	def destroy
		@article = Article.find(params[:id])
		@article.destroy #Elimina el objeto de la BD
		redirect_to articles_path
	end

	#GET /articles/:id/edit
	def edit
		@article = Article.find(params[:id])
	end

	#PUT /article/:id
	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render :edit
		end

	end

	#PUT /articles/:id/publish
	def publish
		@article = Article.find(params[:id])
		@article.publish!
		redirect_to @article
	end

	private 

	def validate_user
		redirect_to new_user_session_path, notice: 'Necesitas iniciar sesión'
	end

	def article_params
		params.require(:article).permit(:title, :body, :cover, :markup)
	end

end

blog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @categories = Category.all
    respond_with(@categories)
  end

  def show
    respond_with(@category)
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.save
    respond_with(@category)
  end

  def update
    @category.update(category_params)
    respond_with(@category)
  end

  def destroy
    @category.destroy
    respond_with(@category)
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :color)
    end
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:update, :destroy, :show]
  before_action :set_article
  respond_to :json

  def show
    respond_with(@comment)
  end


  def create
    @comment = current_user.comments.new(comment_params)
    @comment.article = @article
    @comment.save
    respond_with @comment do |format|
      format.json { render :show , status: "200", location: @comment.article }
    end
  end

  def update
    @comment.update(comment_params)
    respond_with(@comment.article)
  end

  def destroy
    @comment.destroy
    respond_with(@comment.article)
  end

  private
    def set_article
      @article = Article.find(params[:article_id])
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_admin!, only: [:dashboard]

  def index
  end

  def dashboard
  	@articles = Article.paginate(page: params[:page], per_page:5)
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
	def article_cover url, options={}
		html_class = options[:class]
		html_style = " background:url(#{url});"\
					 " width:55%; height:200px;background-size:cover; margin: 0 auto;"
		html = "<header style='#{html_style}' class='#{html_class}'></header>"	
		
		html.html_safe		 		
	end
	
end

blog/app/helpers/categories_helper.rb
module CategoriesHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/articles/_article.html.erb
<div class="col-md-4 top-space">
	<div class="box relative article-height">
		<div class="absolute article-height background-cover" style="background:url(<%= article.cover.url() %>); 
																	 top:0px; left:0px; width:100%;">
			
		</div>
		<div class="absolute article-height background-cover" style="background:rgba(0,0,0,0.5); 
																	 top:0px; left:0px; width:100%;">
			
		</div>
		<div class="relative white text-center">
			<h2><%= link_to article.title, article %></h2>	
			<p><%= truncate( article.body, length:30 ) %></p>
		</div>
	</div>
</div>

blog/app/views/articles/_comments.html.erb
<div class="grey">
	<div class="row">
		<div class="col-xs-6">
			Participa en los comentarios
		</div>
		<div class="col-xs-6">
			<%=@article.comments.count%>
			comentario(s)
		</div>
	</div>
	<div class="field">
		<%=render "comments/form"%>	
	</div>
	<div class="top-space">
		<%=render @article.comments%>	
	</div>
	
</div>

blog/app/views/articles/_formarticle.html.erb
<% name ||= "Articulo" %>
<h1><%= name %></h1>
<%= form_for(@article, html:{id:'article_form'} ) do |f| %>
	<% @article.errors.full_messages.each do |message| %>
		<div style="color:red">
			<%= message %>
		</div>
	<% end %>
	<div class="field">
		<%= f.text_field :title, {placeholder:'Titulo', class:'form-control'} %>
	</div>
	<div class="field">
		Portada: <%= f.file_field :cover %>
	</div>
	<div class="field">
		<%= f.hidden_field :body, {id:'body-textarea'} %>
		<%= f.hidden_field :markup, {id:'body-markup'} %>
		<div id="epiceditor" style="height:350px;"></div>
	</div>
	<div class="field">
		Categorias
		<%@catgs.each do |category|%>
			<div class="field">
				<%= check_box_tag "categories[]", category.id%> <%= category.name %>
			</div>
		<%end%>
	</div>
	<div class="btn">
		<%= f.submit 'Guardar', class:'btn be-green white' %>
	</div>
<%end%>

<script>
var editor = new EpicEditor({
	textarea: 'body-markup',
	file:{
		name:'nuevo_articulo'
	}
});
editor.load();

$("#article_form").on("submit", function(){
	$("#body-textarea").val(editor.exportFile('nuevo_articulo', 'html'));
	$("#body-markup").val(editor.exportFile('nuevo_articulo'));
});
	
</script>

blog/app/views/articles/edit.html.erb
<div style="width:80%; margin: 0 auto;">
	<%= render  "formarticle", name: "Editar Articulo" %>
</div>

blog/app/views/articles/index.html.erb
<div class="container" style="margin: 0 auto;">
	<h1>Articulos</h1>
	<div class="row">
		<%= render @articles %>
	</div>
	<div class="top-space text-center">
		<%= will_paginate @articles %>
	</div>
</div>

blog/app/views/articles/new.html.erb
<div style="width:80%; margin: 0 auto;">
	<%= render  "formarticle", name: "Crear Articulo" %>
</div>

blog/app/views/articles/show.html.erb
<article class="bottom-space">
	<%= article_cover @article.cover.url %>
	<div class="row center-xs">
		<div class="col-xs-12 light-border col-md-7">
			<h1 class="be-big"><%= @article.title %></h1>
			<p class="text-right be-small">
				<%= link_to "Atrás", articles_path , class: "underline"%>
				-
				<span class="red"> <%= @article.visit_counts %> visita(s)</span>
				-
				<%unless @article.user.nil?%>
						Escrito por: <%= @article.user.email%>
				<%end%>
			</p>
			<div class="text-justify"> 
				<%= Sanitize.fragment(@article.body, Sanitize::Config::RELAXED).html_safe %>
			</div>
			<div>
				<%= render "articles/comments"%>
			</div>


			<div><%= link_to "Editar", edit_article_path(@article) %></div>
		</div>
		
	</div>
	
</article>

blog/app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.color_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

blog/app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.color %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

blog/app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

blog/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>



<div class="container" style="margin: 0 auto;">
	<h1 style="color:<%= @category.color %>">
	  <%= @category.name %>
	</h1>

	<div class="row">
		<%= render @category.articles %>
		<%= link_to 'Edit', edit_category_path(@category) %> |
		<%= link_to 'Back', categories_path %>
	</div>
</div>

blog/app/views/comments/_comment.html.erb
<article>
	<header class="text-right be-small">
		<%= time_ago_in_words(comment.created_at) %> - <%= link_to "Borrar", [@article, comment], class:'red' %>
	</header>
	<div class="row">
		<div class="col-xs-1 col-md-1">
			<div class="box">
				<%= image_tag(comment.user.avatar)%>
			</div>
		</div>
		<div class="col-xs-11 col-md-11">
			<div class="box">
				<%= comment.body %>
			</div>
		</div>
	</div>
</article>

blog/app/views/comments/_form.html.erb
<%= form_for([@article, @comment], remote:true, html: {id: "comments-form"} ) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<header>
		<nav class="be-green white large-padding">
			<ul class="no-list row center-xs middle-xs">
				<li>
					<h1 id="logo"><%= link_to "JCompany", root_path %></h1>
				</li>
				<li class="col-md">
					<%= link_to "Articles", articles_path %>
				</li>
				<li class="col-md">
					<%= link_to "Categorias", categories_path %>
				</li>
				<% @catgs.each do |category|%>
					<li class="col-md">
						<%= link_to category.name, category %>
					</li>
				<%end%>
				<% if user_signed_in? %>
					<li class="col-md"><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %>
						
					</li>
				<% else %>
					<li class="col-md"><%= link_to "Iniciar Sesión", new_user_session_path %>
						
					</li>
					<li class="col-md"><%= link_to "Crear Cuenta", new_user_registration_path %>
						
					</li>
				<% end %>
			</ul>
		</nav>
	</header>
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

blog/app/views/welcome/dashboard.html.erb
<% @articles.each do |article| %>
	<h1><%= link_to article.title, article %></h1>

	<div>
	<%= article.body %> 
	- 
	<%= link_to "Eliminar", article, method: :delete%>
	<%if article.may_publish?%>
		- 
		<%= link_to "Publicar", "/articles/#{article.id}/publish", method: :put%>
	<%end%>
	</div>
<% end %>

<%= will_paginate @articles %>

blog/app/views/welcome/index.html.erb
<% if user_signed_in? %>
	<h1>!!Bienvenido <%= current_user.email %>!!</h1>
<%end%>